base:
  name: first-page
  namespace: pastike-com
  env: local

replicaCount: 1

image:
  public: true
  repository: pastikecom/first-page
  tag: latest

service:
  # type: NodePort
  type: ClusterIP
  port: 80
  # targetPort: 80
  # nodePort: 30000

ingress:
  enabled: false
  # tls: letsencrypt
  # hostname: localhost
  # hosts:
  #   - host: first-page-pastike-com.local.localhost
  #     paths:
  #       - path: "/"
  #         pathType: Prefix

resources:
  requests:
    memory: 128Mi
    cpu: 62m
  limits:
    memory: 170Mi
    cpu: 83m
