apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.base.name }}
  namespace: {{ .Values.base.namespace }}
  labels:
    app: {{ .Values.base.name }}-{{ .Values.base.namespace }}
    env: {{ .Values.base.env }}
spec:
  selector:
    app: {{ .Values.base.name }}-{{ .Values.base.namespace }}
    env: {{ .Values.base.env }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- else }}
      targetPort: {{ .Values.service.port }}
      {{- end }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
  type: {{ .Values.service.type }}
